#ifndef CONFIG_USER_H
#define CONFIG_USER_H

/* Select hand configuration */

#define SWAP_SCLN

// #define TAPPING_FORCE_HOLD
#define TAPPING_TERM 300
#define IGNORE_MOD_TAP_INTERRUPT

#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_HUE_STEP 10
#define RGBLIGHT_SAT_STEP 17
#define RGBLIGHT_VAL_STEP 17

#endif // CONFIG_USER_H
